name: blockcanvas
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  get: ^4.6.5
  connectivity_plus: ^2.3.6
  shared_preferences: ^2.0.15
  cached_network_image: ^3.2.1
  flutter_svg: ^0.22.0
  google_sign_in: ^5.0.7
  flutter_login_facebook: ^1.6.2
  flutter_switch: ^0.3.2
  smooth_page_indicator: ^1.0.0+2
  pin_code_fields: ^7.3.0
  sms_autofill: ^2.0.0
  intl: ^0.17.0
  permission_handler: ^10.0.0
  images_picker: ^1.2.11
  url_launcher: 6.0.20
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Urbanist
      fonts: 
        - asset: assets/fonts/UrbanistMedium.ttf
          weight: 500
        - asset: assets/fonts/UrbanistBold.ttf
          weight: 700
        - asset: assets/fonts/UrbanistRegular.ttf
          weight: 400
        - asset: assets/fonts/UrbanistSemiBold.ttf
          weight: 600
